version: "3.2"
services:
  api:
    build:
      context: .
    image: statify/api
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASS=${DB_PASS}
      - MYSQL_DB=${DB_NAME}
    ports:
      - "3000:3000"
    container_name: statify-nodejs-api
    depends_on:
      - mysql
    networks:
      - default
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --secure-file-priv= --local-infile=1
    networks:
      - default
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - persistent:/var/lib/mysql
    container_name: statify-mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    networks:
      - default
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=statify-mysql
      - PMA_PORT= 3306
    container_name: statify-phpmyadmin
volumes:
  persistent:
